import os
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.exc import SQLAlchemyError, IntegrityError
from sqlalchemy import Date, Float, DateTime # Import DateTime for the new column
import logging
from datetime import datetime # Import datetime for timestamping
import numpy as np # Import numpy for numerical truncation

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# --- Configuration ---

# Path to the input CSV file generated by process_weather_data.py
INPUT_CSV_FILE = "stats.csv"

# Azure SQL Database Connection String
AZURE_DB_CONNECTION_STRING = (
)

# Target table name in the Azure SQL database
AZURE_SQL_TABLE_NAME = ""

# Define SQLAlchemy dtype mapping for the target table columns
sql_dtypes_map = {
    'Date': Date,
    'AESO_HDD': Float,
    'AESO_CDD': Float,
    'CYEG_HDD': Float,
    'CYEG_CDD': Float,
    'CYMM_HDD': Float,
    'CYMM_CDD': Float,
    'CYQF_HDD': Float,
    'CYQF_CDD': Float,
    'CYQU_HDD': Float,
    'CYQU_CDD': Float,
    'CYXJ_HDD': Float,
    'CYXJ_CDD': Float,
    'CYYC_HDD': Float,
    'CYYC_CDD': Float,
    'CYYE_HDD': Float,
    'CYYE_CDD': Float,
    'CZPC_HDD': Float,
    'CZPC_CDD': Float,
    'date_published': DateTime # New column for upload timestamp
}

# --- Main Process ---
engine = None
try:
    # --- Extract from CSV ---
    logging.info(f"Attempting to read data from local CSV file: {INPUT_CSV_FILE}")
    if not os.path.exists(INPUT_CSV_FILE):
        logging.error(f"Input CSV file not found at '{INPUT_CSV_FILE}'.")
        exit()

    # Read the CSV into a pandas DataFrame
    df_to_load = pd.read_csv(
        INPUT_CSV_FILE,
        parse_dates=['Date'],  # Parse 'Date' in DD-MMM-YY format
        date_format='%d-%b-%y'  # Specify the exact format
    )

    if df_to_load.empty:
        logging.error("Input CSV file is empty. No data to load. Exiting.")
        exit()

    logging.info(f"Successfully read {len(df_to_load)} rows from '{INPUT_CSV_FILE}'.")

    # Ensure Date is a date object (remove time component)
    df_to_load['Date'] = df_to_load['Date'].dt.date

    # Ensure HDD/CDD columns are floats, fill NaNs with 0, and TRUNCATE to one decimal place
    for col in df_to_load.columns:
        if col.endswith('_HDD') or col.endswith('_CDD'):
            df_to_load[col] = df_to_load[col].fillna(0).astype(float)
            # Truncate to one decimal place: multiply by 10, truncate, then divide by 10
            df_to_load[col] = np.trunc(df_to_load[col] * 10) / 10.0
            logging.debug(f"Truncated column '{col}' to one decimal place.") # Use debug for verbosity

    # --- Add 'date_published' column ---
    # This timestamp will reflect when this batch of data was loaded
    current_publish_time = datetime.now()
    df_to_load['date_published'] = pd.to_datetime(current_publish_time)
    logging.info(f"Added 'date_published' column with current timestamp: {current_publish_time}")

    # Verify DataFrame columns match sql_dtypes_map.keys()
    # First, check for columns that *should* be in the CSV
    csv_required_cols = [col for col in sql_dtypes_map.keys() if col != 'date_published']
    missing_from_csv_cols = [col for col in csv_required_cols if col not in df_to_load.columns]
    if missing_from_csv_cols:
        logging.error(f"Missing essential columns in DataFrame from CSV: {missing_from_csv_cols}")
        exit()

    # Ensure all columns required for SQL are present and correctly ordered,
    # dropping any extra columns from the CSV that are not in sql_dtypes_map
    df_to_load = df_to_load[list(sql_dtypes_map.keys())]
    logging.info("DataFrame columns aligned with SQL schema.")


    # --- Load into Azure SQL Database ---
    logging.info(f"Connecting to Azure SQL Database for table '{AZURE_SQL_TABLE_NAME}'...")
    engine = create_engine(AZURE_DB_CONNECTION_STRING, echo=False, pool_recycle=3600)

    logging.info("Database connection successful.")

    # Insert data into Azure SQL
    logging.info(f"Attempting to insert {len(df_to_load)} rows into Azure SQL table '{AZURE_SQL_TABLE_NAME}'...")
    try:
        df_to_load.to_sql(
            name=AZURE_SQL_TABLE_NAME,
            con=engine,
            if_exists='append',
            index=False,
            dtype=sql_dtypes_map
        )
        logging.info("Data insertion completed.")
        logging.info("Check the Azure SQL table to verify successful insertions.")

    except IntegrityError as ex:
        logging.warning(f"IntegrityError during insertion: {ex}")
        logging.warning("This typically means a unique constraint (e.g., primary key) was violated.")
        logging.warning("If (Date, date_published) forms a unique key, ensure you are not uploading the exact same dataset at the exact same timestamp.")

    except Exception as e:
        logging.error(f"Error during data insertion into Azure SQL: {e}")
        raise

except SQLAlchemyError as ex:
    logging.error(f"A database error occurred: {ex}")
except Exception as e:
    logging.error(f"An unexpected error occurred: {e}")
finally:
    if engine:
        engine.dispose()
        logging.info("Database connection closed.")