# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np
from darts import TimeSeries
from darts.models import NHiTSModel
from darts.dataprocessing.transformers import Scaler as DartsScaler
from darts.metrics import mae, mse
import torch
from pytorch_lightning.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import os
import joblib
import time
import traceback
import sys
import json
from typing import List, Dict, Optional
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# --- Configuration Loading ---
try:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    parent_dir = os.path.abspath(os.path.join(script_dir, '..'))
    if parent_dir not in sys.path:
        sys.path.append(parent_dir)
    from config.settings import BASE_OUTPUT_DIR
    print(f"Loaded BASE_OUTPUT_DIR from config: {BASE_OUTPUT_DIR}")
except (ImportError, NameError, FileNotFoundError) as e:
    print(f"Could not import BASE_OUTPUT_DIR from config.settings ({e}). Using default.")
    BASE_OUTPUT_DIR = "D:\\EIA_STACK"
    print(f"Using default BASE_OUTPUT_DIR: {BASE_OUTPUT_DIR}")

# --- Region and Target Configuration ---
REGION = "southwest"

# Define target columns - Natural Gas
TARGET_COLUMNS = [
    f"{REGION.upper()}_NG_RATIO",
]

# --- File Paths ---
REGION_BASE_DIR = os.path.join(BASE_OUTPUT_DIR, REGION)
FINAL_DIR = os.path.join(REGION_BASE_DIR, "final")
OUTPUT_SUBDIR = "gas_ratio"
MODELS_DIR = os.path.join(REGION_BASE_DIR, "Models", OUTPUT_SUBDIR)
OUTPUT_DIR = os.path.join(REGION_BASE_DIR, OUTPUT_SUBDIR)

# Using parquet files to match coal_ratio script
TRAIN_FILE = os.path.join(FINAL_DIR, "train.parquet")
PREDICT_FILE = os.path.join(FINAL_DIR, "predict.parquet")

# ### NEW: Create backup of original predict.parquet before modifying ###
PREDICT_FILE_BACKUP = os.path.join(FINAL_DIR, "predict_backup_gas.parquet")

# ### NEW: Path to the JSON file containing features to remove ###
# This file is generated by your SHAP analysis script for gas ratio.
REMOVE_FEATURES_JSON = os.path.join(REGION_BASE_DIR, "feature_importance", "ng_ratio_remove.json")

# --- Model Parameters ---
WIDTH_CONFIG = 256
LOSS_FN_CONFIG = torch.nn.SmoothL1Loss()
LOSS_NAME = "smoothl1"
PATIENCE_CONFIG = 7
INPUT_CHUNK_LENGTH = 144
OUTPUT_CHUNK_LENGTH = 12
N_EPOCHS = 100
RANDOM_STATE = 42
LEARNING_RATE = 5e-5
EARLY_STOPPING_PATIENCE = PATIENCE_CONFIG
GRADIENT_CLIP_VAL = 0.1
BATCH_SIZE = 128
DROPOUT = 0.2

# --- NHiTS Architecture ---
COMPAT_NUM_STACKS = 8
COMPAT_NUM_BLOCKS_PER_STACK = 6
NUM_LAYERS_PER_BLOCK = 6
LAYER_WIDTH = WIDTH_CONFIG

# --- Feature Engineering Columns ---
TIME_FEATURE_COLS = ['hour_sin', 'hour_cos', 'weekday_sin', 'weekday_cos', 
                     'month_sin', 'month_cos', 'day_of_year_sin', 'day_of_year_cos', 
                     'weekend', 'year_trend']

# --- Boundary Handling Parameters ---
BRIDGE_HOURS = 168  # 1 week of historical context
BOUNDARY_SMOOTH_HOURS = 6
ANOMALY_THRESHOLD_STD = 2.0

# --- Config Paths ---
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
RETRAIN_CONFIG_FILE = os.path.join(project_root, 'config', 'regions', f"{REGION}_config.json")
if not os.path.exists(RETRAIN_CONFIG_FILE):
    RETRAIN_CONFIG_FILE = os.path.join('..', 'config', 'regions', f"{REGION}_config.json")
    if not os.path.exists(RETRAIN_CONFIG_FILE):
        RETRAIN_CONFIG_FILE = os.path.join('config', 'regions', f"{REGION}_config.json")

# --- Load Configuration ---
FORCE_RETRAIN_NHITS = False
NHITS_RETRAIN_KEY = "force_retrain_NHITS_GasCoalRatio"
BOUNDARY_CONFIG = {
    'enabled': True,
    'bridge_hours': BRIDGE_HOURS,
    'smooth_hours': BOUNDARY_SMOOTH_HOURS,
    'anomaly_threshold': ANOMALY_THRESHOLD_STD
}

print(f"\nAttempting to load retraining configuration from: {RETRAIN_CONFIG_FILE}")
if os.path.exists(RETRAIN_CONFIG_FILE):
    try:
        with open(RETRAIN_CONFIG_FILE, 'r') as f:
            retrain_config = json.load(f)
        FORCE_RETRAIN_NHITS = retrain_config.get(NHITS_RETRAIN_KEY, False)
        if "boundary_handling" in retrain_config:
            BOUNDARY_CONFIG.update(retrain_config["boundary_handling"])
        print(f"  Loaded '{NHITS_RETRAIN_KEY}': {FORCE_RETRAIN_NHITS}")
        print(f"  Boundary handling config: {BOUNDARY_CONFIG}")
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from '{RETRAIN_CONFIG_FILE}'. Defaulting to False.")
    except Exception as e:
        print(f"Error reading retrain config: {e}. Defaulting to False.")
        traceback.print_exc()
else:
    print(f"Warning: Retraining config file '{RETRAIN_CONFIG_FILE}' not found. Defaulting to False.")

# ### NEW: Load the list of features to remove ###
features_to_remove = []
if os.path.exists(REMOVE_FEATURES_JSON):
    print(f"\nLoading feature removal list from: {REMOVE_FEATURES_JSON}")
    try:
        with open(REMOVE_FEATURES_JSON, 'r') as f:
            features_to_remove = json.load(f)
        print(f"  Successfully loaded {len(features_to_remove)} features to remove based on SHAP analysis.")
        if len(features_to_remove) > 0:
            print(f"  First 5 features to remove: {features_to_remove[:5]}")
    except Exception as e:
        print(f"  WARNING: Could not load or parse feature removal list. Using all features. Error: {e}")
        features_to_remove = []
else:
    print(f"\n  INFO: No feature removal list found at {REMOVE_FEATURES_JSON}. Using all available features.")

# Ensure directories exist
os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(FINAL_DIR, exist_ok=True)

# --- Output File Naming ---
MODEL_VERSION_SUFFIX = f"_GasCoalRatio_NoTargetScaling_Seamless_SHAP"
MODEL_SAVE_PATH = os.path.join(MODELS_DIR, f"nhits_model_final{MODEL_VERSION_SUFFIX}.pt")
# ### MODIFIED: We'll still save a separate output file for reference/debugging ###
OUTPUT_FILE_REFERENCE = os.path.join(OUTPUT_DIR, f"{REGION}_predicted_gas_ratio_reference.parquet")
SKLEARN_SCALERS_PATH = os.path.join(MODELS_DIR, f"sklearn_cov_scalers{MODEL_VERSION_SUFFIX}.joblib")
SCALER_INFO_SAVE_PATH = os.path.join(MODELS_DIR, f"scaler_info{MODEL_VERSION_SUFFIX}.joblib")

# --- Print Configuration ---
print("="*50)
print(f"--- NHITS FINAL MODEL (Gas Ratio - NO TARGET SCALING) WITH SEAMLESS BRIDGING ---")
print(f"--- REGION: {REGION.upper()} ---")
print(f"--- Targets: {TARGET_COLUMNS} ---")
print("--- Will OVERWRITE target columns in predict.parquet ---")
print("="*50)
print(f"Using Input Files:\n  Train: {TRAIN_FILE}\n  Predict: {PREDICT_FILE}")
print(f"NHiTS Config: I={INPUT_CHUNK_LENGTH}, O={OUTPUT_CHUNK_LENGTH}, Stacks={COMPAT_NUM_STACKS}, Width={WIDTH_CONFIG}")
print(f"Training Params: Loss={LOSS_NAME.upper()}, Epochs={N_EPOCHS}, Patience={EARLY_STOPPING_PATIENCE}, LR={LEARNING_RATE}")
print(f"Boundary Handling: Bridge={BOUNDARY_CONFIG['bridge_hours']}h, Smooth={BOUNDARY_CONFIG['smooth_hours']}h")
print(f"Target Scaling: OFF")
if len(features_to_remove) > 0:
    print(f"Feature Selection: Removing {len(features_to_remove)} features based on SHAP analysis")
print(f"Model save path: {MODEL_SAVE_PATH}")
print(f"Predict file will be OVERWRITTEN: {PREDICT_FILE}")
print(f"Reference output: {OUTPUT_FILE_REFERENCE}")
print(f"Covariate Scalers path: {SKLEARN_SCALERS_PATH}")
print(f"Force Retrain (from config or default): {FORCE_RETRAIN_NHITS}")
print("="*50)

# -------------------------------------------
# Feature Engineering Functions (Simplified)
# -------------------------------------------
def create_time_features(df, date_col='date', min_year_train=None):
    """Creates standard time-based features."""
    if date_col not in df.columns: 
        print(f"Error: Date col '{date_col}' missing.")
        return df, []
    try: 
        df[date_col] = pd.to_datetime(df[date_col])
    except Exception as e: 
        print(f"Error parsing date column '{date_col}': {e}")
        return df, []
    if not pd.api.types.is_datetime64_any_dtype(df[date_col]): 
        print(f"Warning: '{date_col}' not datetime.")
        return df, []
    features = {}
    dt = df[date_col].dt
    try:
        features['hour_sin'] = np.sin(2 * np.pi * dt.hour / 24)
        features['hour_cos'] = np.cos(2 * np.pi * dt.hour / 24)
        features['weekday_sin'] = np.sin(2 * np.pi * dt.dayofweek / 7)
        features['weekday_cos'] = np.cos(2 * np.pi * dt.dayofweek / 7)
        features['month_sin'] = np.sin(2 * np.pi * dt.month / 12)
        features['month_cos'] = np.cos(2 * np.pi * dt.month / 12)
        features['day_of_year_sin'] = np.sin(2 * np.pi * dt.dayofyear / 365.25)
        features['day_of_year_cos'] = np.cos(2 * np.pi * dt.dayofyear / 365.25)
        features['weekend'] = dt.dayofweek.isin([5, 6]).astype(int)
        if min_year_train: 
            features['year_trend'] = dt.year - min_year_train
        time_features_df = pd.DataFrame(features, index=df.index)
        time_feature_cols = list(features.keys())
        cols_to_drop = [col for col in time_features_df.columns if col in df.columns]
        df = pd.concat([df.drop(columns=cols_to_drop, errors='ignore'), time_features_df], axis=1)
        print(f"  Added/updated time features: {time_feature_cols}")
        return df, time_feature_cols
    except Exception as e: 
        print(f"Error creating time features: {e}")
        return df, []

# -------------------------------------------
# Seamless Data Creation Function
# -------------------------------------------
def create_seamless_prediction_data(
    train_file_path: str,
    predict_file_path: str,
    target_cols: List[str],
    date_col: str,
    bridge_hours: int = 168,
    overlap_hours: int = 0,
    features_to_remove: list = []
):
    """
    Create a seamless prediction dataset by bridging train and predict files.
    Modified to load PARQUET files.
    """
    print(f"\n--- Creating Seamless Prediction Data ---")

    # Load both files from .parquet
    df_train = pd.read_parquet(train_file_path)
    df_predict = pd.read_parquet(predict_file_path)

    # Ensure date column is datetime
    df_train[date_col] = pd.to_datetime(df_train[date_col])
    df_predict[date_col] = pd.to_datetime(df_predict[date_col])

    # Sort by date
    df_train = df_train.sort_values(date_col).reset_index(drop=True)
    df_predict = df_predict.sort_values(date_col).reset_index(drop=True)

    # Get time boundaries
    train_end = df_train[date_col].max()
    predict_start = df_predict[date_col].min()

    print(f"Train ends at: {train_end}")
    print(f"Predict starts at: {predict_start}")

    # Check for gap or overlap
    time_diff = (predict_start - train_end).total_seconds() / 3600
    if time_diff > 1:
        print(f"WARNING: {time_diff:.1f} hour gap between train and predict!")
    elif time_diff < -1:
        print(f"Found {-time_diff:.1f} hour overlap between files")

    # Extract bridge data from training set
    bridge_start = train_end - pd.Timedelta(hours=bridge_hours)
    df_bridge = df_train[df_train[date_col] > bridge_start].copy()

    print(f"Extracting {len(df_bridge)} hours of bridge data from training set")

    # Remove overlap from prediction data if needed
    if overlap_hours > 0:
        overlap_cutoff = predict_start + pd.Timedelta(hours=overlap_hours)
        df_predict = df_predict[df_predict[date_col] >= overlap_cutoff].copy()
        print(f"Removed {overlap_hours} hours of overlap from prediction data")

    # Combine datasets
    df_seamless = pd.concat([df_bridge, df_predict], ignore_index=True)
    df_seamless = df_seamless.sort_values(date_col).reset_index(drop=True)

    # Add flags to identify data source
    df_seamless['data_source'] = 'future'
    df_seamless.loc[df_seamless[date_col] <= train_end, 'data_source'] = 'historical'

    # Ensure no duplicates
    df_seamless = df_seamless.drop_duplicates(subset=[date_col], keep='first')

    print(f"Created seamless dataset with {len(df_seamless)} total hours")
    print(f"  - Historical (from train): {(df_seamless['data_source'] == 'historical').sum()} hours")
    print(f"  - Future (from predict): {(df_seamless['data_source'] == 'future').sum()} hours")

    # Calculate actual forecast start (first hour after training data)
    actual_forecast_start = train_end + pd.Timedelta(hours=1)

    return df_seamless, actual_forecast_start

# -------------------------------------------
# Boundary Smoothing Functions
# -------------------------------------------
def apply_boundary_smoothing(df_pred, hist_stats, date_col, pred_cols,
                           smooth_hours=6, anomaly_threshold=2.0):
    """Apply intelligent smoothing based on historical patterns for multiple targets"""

    if df_pred.empty:
        return df_pred

    df_pred = df_pred.sort_values(date_col).reset_index(drop=True)

    for pred_col in pred_cols:
        if pred_col not in df_pred.columns or pred_col not in hist_stats:
            continue

        stats = hist_stats[pred_col]

        # Check for boundary anomaly
        first_pred = df_pred.iloc[0][pred_col]
        last_hist = stats['last_value']
        jump = first_pred - last_hist
        jump_z_score = abs(jump) / stats['std'] if stats['std'] > 0 else 0

        print(f"\n{pred_col} - Boundary jump: {jump:.4f} (z-score: {jump_z_score:.2f})")

        if jump_z_score > anomaly_threshold:
            print(f"Applying boundary smoothing (jump exceeds {anomaly_threshold} std devs)")

            # Exponential smoothing of the jump
            for i in range(min(smooth_hours, len(df_pred))):
                decay = np.exp(-i / (smooth_hours / 3))
                adjustment = jump * decay
                df_pred.loc[i, pred_col] = df_pred.loc[i, pred_col] - adjustment

            # Also apply confidence-based clipping for first 24 hours
            for i in range(min(24, len(df_pred))):
                confidence = i / 24  # 0 to 1 over 24 hours

                # For ratios, we have natural bounds [0, 1]
                max_deviation = stats['std'] * (anomaly_threshold + confidence * 2)
                upper_bound = min(1.0, last_hist + max_deviation)
                lower_bound = max(0.0, last_hist - max_deviation)

                # Add trend component to bounds if available
                if 'recent_trend' in stats and stats['recent_trend'] is not None:
                    trend_component = stats['recent_trend'] * (i + 1)
                    upper_bound = min(1.0, upper_bound + max(0, trend_component))
                    lower_bound = max(0.0, lower_bound + min(0, trend_component))

                # Store original value for comparison
                original = df_pred.loc[i, pred_col]
                clipped = np.clip(original, lower_bound, upper_bound)

                if original != clipped:
                    print(f"  Hour {i}: Clipped {original:.4f} to {clipped:.4f}")
                    df_pred.loc[i, pred_col] = clipped

    return df_pred

# -------------------------------------------
# Data Loading & Preparation
# -------------------------------------------
print(f"\n--- Loading Training Data: {TRAIN_FILE} ---")
try:
    # Load from .parquet file
    df_train_full = pd.read_parquet(TRAIN_FILE)
    df_train_full['date'] = pd.to_datetime(df_train_full['date'])  # Ensure datetime type
    df_train_full = df_train_full.sort_values("date").reset_index(drop=True)
    print(f"Loaded Training Data shape: {df_train_full.shape}")
    date_col_name = "date"
    
    # Validate targets exist
    missing_targets = [col for col in TARGET_COLUMNS if col not in df_train_full.columns]
    if missing_targets: 
        raise ValueError(f"Required target columns missing in {TRAIN_FILE}: {missing_targets}")
    print(f"Found all target columns: {TARGET_COLUMNS}")
    
    # Handle NaNs in targets
    for target_col in TARGET_COLUMNS:
        if df_train_full[target_col].isnull().any(): 
            print(f"Warning: NaNs found in target '{target_col}'. Interpolating...")
            df_train_full[target_col] = df_train_full[target_col].interpolate(method='linear').ffill().bfill()
        if df_train_full[target_col].isnull().any(): 
            raise ValueError(f"NaNs persist in target '{target_col}' after interpolation.")
    
    # Handle duplicates
    if df_train_full[date_col_name].duplicated().any(): 
        print("Warning: Duplicate dates found in training file. Keeping first.")
        df_train_full = df_train_full.drop_duplicates(subset=[date_col_name], keep='first')

    # --- Covariate Identification and Filtering ---
    print("\nIdentifying and filtering covariates...")
    all_columns = df_train_full.columns.tolist()
    cols_to_exclude_base = [date_col_name] + TARGET_COLUMNS
    initial_potential_covariates = [col for col in all_columns if col not in cols_to_exclude_base]

    print(f"  Total potential covariates before filtering: {len(initial_potential_covariates)}")

    # --- Filter out specific column patterns ---
    columns_to_exclude_patterns = ["_MW", "_NG_RATIO",
                                  "_Hydroelectric,_Coal", "_Ng,_Nuclear", "_Other", "_Solar", "_Wind"]
    additional_exclusions = []
    for col in initial_potential_covariates:
        col_upper = col.upper()
        for pattern in columns_to_exclude_patterns:
            if col_upper.endswith(pattern):
                additional_exclusions.append(col)
                break

    if additional_exclusions:
        print(f"  Excluded {len(additional_exclusions)} columns based on naming conventions")

    pre_filtered_covariates = [
        col for col in initial_potential_covariates if col not in additional_exclusions
    ]

    # ### Apply the feature removal list from SHAP analysis ###
    final_covariate_columns = []
    shap_removed_features = []

    for col in pre_filtered_covariates:
        if col not in features_to_remove:
            final_covariate_columns.append(col)
        else:
            shap_removed_features.append(col)

    if shap_removed_features:
        print(f"  Removed {len(shap_removed_features)} features based on SHAP analysis")
        print(f"    Sample of removed features: {shap_removed_features[:5]}")

    final_covariate_columns = sorted(final_covariate_columns)
    print(f"\n  Final number of covariate columns to use: {len(final_covariate_columns)}")

    if not final_covariate_columns:
        print("Warning: No covariate columns identified.")
    else:
        print(f"  Final Covariates (first 10): {final_covariate_columns[:10]}")

    # Check and fill NaNs in the final selected covariates BEFORE scaling
    if final_covariate_columns:
        nan_cov_check = df_train_full[final_covariate_columns].isnull().sum()
        if nan_cov_check.sum() > 0:
            print(f"Found NaNs in selected covariates:\n{nan_cov_check[nan_cov_check > 0]}. Filling with ffill/bfill/0.")
            df_train_full[final_covariate_columns] = df_train_full[final_covariate_columns].ffill().bfill().fillna(0)
            if df_train_full[final_covariate_columns].isnull().sum().sum() > 0:
                print("ERROR: NaNs still present in covariates after filling!")
                sys.exit(1)

    print(f"Final Training Data shape after prep: {df_train_full.shape}")
    print(f"Using {len(final_covariate_columns)} features (after removing {len(features_to_remove)} features)")

except Exception as e: 
    print(f"ERROR loading/preparing training data: {e}")
    traceback.print_exc()
    sys.exit(1)

min_train_year = df_train_full[date_col_name].dt.year.min()

# --- Create Darts TimeSeries ---
print("Creating Darts TimeSeries objects...")
try:
    target_series_full = TimeSeries.from_dataframe(
        df_train_full, time_col=date_col_name, value_cols=TARGET_COLUMNS, 
        freq="h", fill_missing_dates=False
    )
    print(f"Target Darts TimeSeries created. Range: {target_series_full.start_time()} to {target_series_full.end_time()} ({len(target_series_full)} points).")
    print(f"Components ({target_series_full.width}): {list(target_series_full.components)}")
    
    covariate_series_full = None
    if final_covariate_columns:
        covariate_series_full = TimeSeries.from_dataframe(
            df_train_full, time_col=date_col_name, value_cols=final_covariate_columns, 
            freq="h", fill_missing_dates=False
        )
        print(f"Covariate Darts TimeSeries created ({covariate_series_full.width} components).")
except Exception as e: 
    print(f"ERROR creating Darts TimeSeries: {e}")
    traceback.print_exc()
    sys.exit(1)

# --- Scaling ---
print("\n--- Scaling Covariates (NO Target Scaling) ---")
covariate_series_PRESCALED_full = None
scalers = {}

if covariate_series_full:
    print("Fitting covariate scaler (StandardScaler)...")
    covariate_scaler = StandardScaler()
    try:
        scaler_input_df = covariate_series_full.to_dataframe()
        covariate_scaler.fit(scaler_input_df)
        scalers['covariates'] = covariate_scaler
        print(f"Fitted StandardScaler for all {len(final_covariate_columns)} covariates.")

        # ### Save scaler info including features_removed ###
        scaler_info = {
            'all_covariate_cols': final_covariate_columns,
            'covariate_components_order': list(covariate_series_full.components),
            'min_train_year': min_train_year,
            'features_removed': features_to_remove  # Save this for reference
        }
        joblib.dump(scaler_info, SCALER_INFO_SAVE_PATH)
        print(f"Scaler info saved to {SCALER_INFO_SAVE_PATH}")

        joblib.dump(scalers, SKLEARN_SCALERS_PATH)
        print(f"Sklearn covariate scaler saved to {SKLEARN_SCALERS_PATH}")
        
        print("Transforming full covariate TimeSeries...")
        darts_cov_scaler = DartsScaler(scaler=scalers['covariates'], name="StdScalerCov", n_jobs=-1)
        covariate_series_PRESCALED_full = darts_cov_scaler.fit_transform(covariate_series_full)
        print(f"Full covariate series scaled ({covariate_series_PRESCALED_full.width} components).")
        
        if covariate_series_PRESCALED_full.pd_dataframe().isnull().any().any():
            print("ERROR: NaNs in scaled covariates! Check scaling.")
            sys.exit(1)
    except Exception as e:
        print(f"ERROR during covariate scaling: {e}")
        traceback.print_exc()
        covariate_series_PRESCALED_full = None
else:
    print("No covariates identified. Skipping covariate scaling.")

# --- Model Definition (Helper Function) ---
def create_nhits_model(input_chunk, output_chunk, n_epochs, patience, loss_fn, lr, grad_clip, batch_size, dropout, 
                      num_stacks, num_blocks, num_layers, layer_width, random_state):
    print("Defining N-HiTS model instance...")
    early_stopper = EarlyStopping(monitor="train_loss", patience=patience, min_delta=0.0001, mode='min', verbose=True)
    callbacks_list = [early_stopper]
    try: 
        model = NHiTSModel(
            input_chunk_length=input_chunk, 
            output_chunk_length=output_chunk, 
            num_stacks=num_stacks, 
            num_blocks=num_blocks, 
            num_layers=num_layers, 
            layer_widths=layer_width, 
            dropout=dropout, 
            n_epochs=n_epochs, 
            random_state=random_state, 
            loss_fn=loss_fn, 
            optimizer_kwargs={"lr": lr}, 
            pl_trainer_kwargs={"accelerator": "auto", "callbacks": callbacks_list, "gradient_clip_val": grad_clip}, 
            batch_size=batch_size, 
            force_reset=True, 
            save_checkpoints=False, 
            likelihood=None
        )
        return model
    except Exception as e: 
        print(f"ERROR initializing NHiTSModel: {e}")
        traceback.print_exc()
        return None

# --- Final Model Training (No CV) ---
print("\n--- Training Final Model on Full Dataset (No CV) ---")
final_model = None
model_exists = os.path.exists(MODEL_SAVE_PATH)
can_train_final = True

if target_series_full is None: 
    print("ERROR: Target TimeSeries is None.")
    can_train_final = False
if final_covariate_columns and covariate_series_PRESCALED_full is None: 
    print("ERROR: Covariates identified but scaled series creation failed.")
    can_train_final = False

force_retrain_decision = FORCE_RETRAIN_NHITS

if not can_train_final: 
    print("Skipping final model training due to previous errors.")
elif model_exists and not force_retrain_decision:
    try: 
        print(f"Loading existing model: {MODEL_SAVE_PATH}...")
        final_model = NHiTSModel.load(MODEL_SAVE_PATH)
        print("Loaded.")
    except Exception as e: 
        print(f"Error loading model: {e}. Forcing retrain.")
        force_retrain_decision = True
        final_model = None
else:
    if not model_exists: 
        print(f"Model not found at {MODEL_SAVE_PATH}. Training.")
    elif force_retrain_decision: 
        print(f"Force Retrain is True (from config: {FORCE_RETRAIN_NHITS}). Training.")
    force_retrain_decision = True

if final_model is None and force_retrain_decision and can_train_final:
    print("Instantiating final model...")
    final_model = create_nhits_model(
        input_chunk=INPUT_CHUNK_LENGTH, 
        output_chunk=OUTPUT_CHUNK_LENGTH, 
        n_epochs=N_EPOCHS, 
        patience=EARLY_STOPPING_PATIENCE, 
        loss_fn=LOSS_FN_CONFIG, 
        lr=LEARNING_RATE, 
        grad_clip=GRADIENT_CLIP_VAL, 
        batch_size=BATCH_SIZE, 
        dropout=DROPOUT, 
        num_stacks=COMPAT_NUM_STACKS, 
        num_blocks=COMPAT_NUM_BLOCKS_PER_STACK, 
        num_layers=NUM_LAYERS_PER_BLOCK, 
        layer_width=LAYER_WIDTH, 
        random_state=RANDOM_STATE
    )
    if final_model:
        print("Training final model...")
        start_train_time = time.time()
        fit_kwargs = {'series': target_series_full, 'verbose': True}
        try:
            if covariate_series_PRESCALED_full:
                print(f"  Providing {covariate_series_PRESCALED_full.width} scaled past covariates to fit().")
                fit_kwargs['past_covariates'] = covariate_series_PRESCALED_full
            else:
                print("  No past covariates provided to fit().")

            final_model.fit(**fit_kwargs)
            end_train_time = time.time()
            print(f"Final training took {end_train_time - start_train_time:.2f} sec.")
            print(f"Saving final model: {MODEL_SAVE_PATH}...")
            final_model.save(MODEL_SAVE_PATH)
            print("Saved.")
        except Exception as e: 
            print(f"Error training/saving: {e}")
            traceback.print_exc()
            final_model = None
    else: 
        print("ERROR: Failed to create final model instance.")

if final_model is None: 
    print("FATAL ERROR: No model available for inference.")
    sys.exit(1)

# -------------------------------------------
# Enhanced Inference Function with Direct Overwrite (MODIFIED)
# -------------------------------------------
def do_inference_seamless_and_overwrite(
    model_to_use: NHiTSModel,
    train_file_path: str,
    predict_file_path: str,
    path_to_sklearn_scalers: str,
    path_to_scaler_info: str,
    target_cols_list: list,
    expected_covariate_cols: list,
    date_col_name: str = "date",
    bridge_hours: int = 168,
    boundary_smooth_hours: int = 6,
    anomaly_threshold: float = 2.0,
    min_year_train: int = None,
    time_feature_cols: list = TIME_FEATURE_COLS,
    backup_predict_file: bool = True,
    reference_output_path: str = None
):
    """
    Perform inference using seamless data bridging and OVERWRITE the predict.parquet file.
    """
    print(f"\n--- Starting Enhanced Inference with Direct Overwrite ---")
    start_time = time.time()
    
    # ### NEW: Create backup of predict.parquet before modifying ###
    if backup_predict_file and os.path.exists(predict_file_path):
        backup_path = predict_file_path.replace('.parquet', '_backup_gas.parquet')
        print(f"Creating backup of predict.parquet at: {backup_path}")
        try:
            import shutil
            shutil.copy2(predict_file_path, backup_path)
            print("Backup created successfully.")
        except Exception as e:
            print(f"WARNING: Could not create backup: {e}")

    # Step 1: Load the original predict.parquet to preserve all columns
    print(f"\nLoading original predict.parquet from: {predict_file_path}")
    df_predict_original = pd.read_parquet(predict_file_path)
    df_predict_original[date_col_name] = pd.to_datetime(df_predict_original[date_col_name])
    print(f"Original predict.parquet shape: {df_predict_original.shape}")
    print(f"Target columns to be replaced: {target_cols_list}")

    # Step 2: Create seamless dataset (passing features_to_remove)
    df_seamless, actual_forecast_start = create_seamless_prediction_data(
        train_file_path=train_file_path,
        predict_file_path=predict_file_path,
        target_cols=target_cols_list,
        date_col=date_col_name,
        bridge_hours=bridge_hours,
        features_to_remove=features_to_remove  # Pass the global features_to_remove list
    )

    # Step 3: Load scalers and info
    local_cov_scalers_dict = {}
    scaler_info = None

    if path_to_sklearn_scalers and os.path.exists(path_to_sklearn_scalers):
        try:
            local_cov_scalers_dict = joblib.load(path_to_sklearn_scalers)
            print("Covariate scalers dict loaded.")
        except Exception as e:
            print(f"Warn: Failed load cov scalers: {e}")
    else:
        print("Warn: Covariate scalers path missing or not found. Covariates will not be scaled.")

    if path_to_scaler_info and os.path.exists(path_to_scaler_info):
        try:
            scaler_info = joblib.load(path_to_scaler_info)
            print("Scaler info loaded.")
            # Check if the saved model used the same feature removal
            if 'features_removed' in scaler_info:
                saved_features_removed = scaler_info['features_removed']
                if set(saved_features_removed) != set(features_to_remove):
                    print("WARNING: Feature removal list differs from what was used in training!")
                    print(f"  Training removed: {len(saved_features_removed)} features")
                    print(f"  Current list has: {len(features_to_remove)} features")
        except Exception as e:
            print(f"Warning: Failed to load scaler info: {e}")

    # Step 4: Prepare features for seamless data
    # Remove features from seamless data based on removal list
    cols_to_drop = [col for col in features_to_remove if col in df_seamless.columns]
    if cols_to_drop:
        print(f"Removing {len(cols_to_drop)} features from seamless data based on removal list")
        df_seamless = df_seamless.drop(columns=cols_to_drop)

    # Generate any missing features (that are not in the removal list)
    missing_cols = [c for c in expected_covariate_cols if c not in df_seamless.columns]
    if missing_cols:
        print(f"Generating missing features: {len(missing_cols)} features")
        time_features_to_gen = [tf for tf in time_feature_cols if tf in missing_cols]
        if time_features_to_gen:
            print("Regenerating time features...")
            df_seamless, _ = create_time_features(df_seamless, date_col_name, min_year_train)

        # Remove any generated features that are in the removal list
        cols_to_drop_after_gen = [col for col in features_to_remove if col in df_seamless.columns]
        if cols_to_drop_after_gen:
            df_seamless = df_seamless.drop(columns=cols_to_drop_after_gen)

        # Check again
        still_missing = [c for c in expected_covariate_cols if c not in df_seamless.columns]
        if still_missing:
            print(f"Warning: Still missing non-time covariates: {len(still_missing)} columns. Filling with 0.")
            print(f"  Sample of missing: {still_missing[:5]}")
            for col in still_missing:
                df_seamless[col] = 0

    # Fill any NaNs in covariates
    if expected_covariate_cols:
        # Only fill NaNs for columns that exist and are expected
        existing_expected_cols = [c for c in expected_covariate_cols if c in df_seamless.columns]
        nan_counts = df_seamless[existing_expected_cols].isnull().sum()
        if nan_counts.sum() > 0:
            print("Filling NaNs in covariates...")
            df_seamless[existing_expected_cols] = df_seamless[existing_expected_cols].ffill().bfill().fillna(0)

    # Step 5: Split seamless data into historical and future
    df_historical = df_seamless[df_seamless[date_col_name] < actual_forecast_start].copy()
    df_future = df_seamless[df_seamless[date_col_name] >= actual_forecast_start].copy()

    print(f"\nSplit seamless data at {actual_forecast_start}:")
    print(f"  - Historical (with bridge): {len(df_historical)} hours")
    print(f"  - Future to predict: {len(df_future)} hours")

    # Step 6: Create TimeSeries objects
    # Historical targets (includes bridge data) - NO SCALING for targets
    hist_target_unscaled = None
    if all(col in df_historical.columns for col in target_cols_list):
        hist_target_unscaled = TimeSeries.from_dataframe(
            df_historical, date_col_name, target_cols_list, freq='h'
        )
        print(f"Historical target TimeSeries created: {len(hist_target_unscaled)} timesteps")

    # Covariates for entire span (historical + future)
    seamless_cov_scaled = None
    if expected_covariate_cols:
        # Ensure column order matches training
        cols_for_ts = [c for c in expected_covariate_cols if c in df_seamless.columns]

        if cols_for_ts:
            seamless_cov_ts = TimeSeries.from_dataframe(
                df_seamless, date_col_name, cols_for_ts, freq='h',
                fill_missing_dates=True, fillna_value=0
            )

            # Scale covariates if scaler available
            if 'covariates' in local_cov_scalers_dict:
                print("Scaling seamless covariates...")
                try:
                    darts_cov_scaler_inf = DartsScaler(scaler=local_cov_scalers_dict['covariates'], name="StdScalerCovInf", n_jobs=-1)
                    darts_cov_scaler_inf.fit(seamless_cov_ts)
                    seamless_cov_scaled = darts_cov_scaler_inf.transform(seamless_cov_ts)
                    print(f"Scaled seamless covariates: {seamless_cov_scaled.width} components, {len(seamless_cov_scaled)} timesteps")
                except Exception as e:
                    print(f"Error scaling seamless covariates: {e}")
                    seamless_cov_scaled = seamless_cov_ts
            else:
                print("No covariate scaler available, using unscaled covariates")
                seamless_cov_scaled = seamless_cov_ts

    # Step 7: Calculate historical statistics for boundary checking
    hist_stats = {}
    for target_col in target_cols_list:
        if target_col in df_historical.columns:
            # Get last week of historical data
            week_ago = actual_forecast_start - pd.Timedelta(hours=168)
            recent_history = df_historical[df_historical[date_col_name] >= week_ago][target_col]

            if len(recent_history) > 0:
                hist_stats[target_col] = {
                    'mean': recent_history.mean(),
                    'std': recent_history.std(),
                    'last_value': recent_history.iloc[-1],
                    'recent_trend': np.mean(np.diff(recent_history.tail(24))) if len(recent_history) >= 24 else 0
                }
                print(f"\nHistorical stats for {target_col} from bridge data:")
                print(f"  Mean: {hist_stats[target_col]['mean']:.4f}")
                print(f"  Std: {hist_stats[target_col]['std']:.4f}")
                print(f"  Last value: {hist_stats[target_col]['last_value']:.4f}")
                print(f"  Recent trend: {hist_stats[target_col]['recent_trend']:.6f}/hour")

    # Step 8: Generate predictions
    n_predict = len(df_future)
    print(f"\nGenerating {n_predict} predictions...")

    predictions_unscaled = None
    try:
        # Prepare prediction inputs
        predict_kwargs = {'n': n_predict, 'verbose': True}

        # Add historical series if needed
        if model_to_use.input_chunk_length > 0:
            if hist_target_unscaled is None:
                raise ValueError("Model requires historical target data but none available")

            # Get the right chunk of history for prediction start
            hist_end = actual_forecast_start - pd.Timedelta(hours=1)
            hist_start = hist_end - pd.Timedelta(hours=model_to_use.input_chunk_length - 1)

            predict_series = hist_target_unscaled.slice(hist_start, hist_end)
            if len(predict_series) != model_to_use.input_chunk_length:
                raise ValueError(f"Historical chunk wrong size: {len(predict_series)} vs {model_to_use.input_chunk_length}")

            predict_kwargs['series'] = predict_series

        # Add covariates if available
        if seamless_cov_scaled is not None:
            predict_kwargs['past_covariates'] = seamless_cov_scaled

        # Generate predictions
        predictions_unscaled = model_to_use.predict(**predict_kwargs)

    except Exception as e:
        print(f"ERROR during prediction: {e}")
        traceback.print_exc()
        return df_predict_original  # Return original if prediction fails

    # Step 9: Post-process predictions
    if predictions_unscaled is None:
        print("ERROR: No predictions generated")
        return df_predict_original

    # Convert to dataframe
    df_pred_raw = predictions_unscaled.to_dataframe().reset_index()
    df_pred_raw.rename(columns={"time": date_col_name}, inplace=True)
    df_pred_raw[date_col_name] = pd.to_datetime(df_pred_raw[date_col_name])

    print("  (Skipping growth bump for ratio predictions)")

    # Keep only the predicted values for target columns
    df_predictions = df_pred_raw[[date_col_name] + target_cols_list].copy()

    # Clip predictions to [0, 1] for ratios
    for col in target_cols_list:
        if col in df_predictions.columns and "_RATIO" in col.upper():
            print(f"Clipping {col} to [0, 1]")
            df_predictions[col] = np.clip(df_predictions[col], 0, 1)

    # Step 10: Apply boundary smoothing if needed
    if hist_stats and boundary_smooth_hours > 0 and BOUNDARY_CONFIG['enabled']:
        print("\nChecking for boundary anomalies...")
        df_predictions = apply_boundary_smoothing(
            df_predictions, hist_stats, date_col_name,
            target_cols_list, boundary_smooth_hours, anomaly_threshold
        )

    # Step 11: OVERWRITE target columns in original predict.parquet
    print(f"\n--- Overwriting target columns in predict.parquet ---")
    
    # Merge predictions with original data
    df_updated = df_predict_original.copy()
    
    # Drop the old target columns from the updated dataframe
    for target_col in target_cols_list:
        if target_col in df_updated.columns:
            print(f"Dropping old column: {target_col}")
            df_updated = df_updated.drop(columns=[target_col])
    
    # Merge in the new predictions
    df_updated = pd.merge(df_updated, df_predictions, on=date_col_name, how='left')
    
    # Verify the merge
    print(f"Updated dataframe shape: {df_updated.shape}")
    print(f"Original dataframe shape: {df_predict_original.shape}")
    
    # Check that all target columns have been updated
    for target_col in target_cols_list:
        if target_col not in df_updated.columns:
            print(f"WARNING: Target column {target_col} not in updated dataframe!")
        else:
            nan_count = df_updated[target_col].isna().sum()
            print(f"  {target_col}: {len(df_updated) - nan_count}/{len(df_updated)} values filled")

    # Step 12: Save the updated dataframe back to predict.parquet
    print(f"\nOverwriting predict.parquet at: {predict_file_path}")
    try:
        df_updated.to_parquet(predict_file_path, index=False)
        print("Successfully overwrote predict.parquet with new predictions!")
    except Exception as e:
        print(f"ERROR: Could not save updated predict.parquet: {e}")
        return df_predict_original

    # Step 13: Optionally save a reference copy for debugging
    if reference_output_path:
        print(f"\nSaving reference copy to: {reference_output_path}")
        try:
            df_predictions.to_parquet(reference_output_path, index=False)
            print("Reference copy saved successfully.")
        except Exception as e:
            print(f"Warning: Could not save reference copy: {e}")

    end_time = time.time()
    print(f"\nInference and overwrite completed in {end_time - start_time:.2f} seconds")

    return df_updated

# -------------------------------------------
# Main Execution Block
# -------------------------------------------
if __name__ == "__main__":
    print("\n--- Main Execution: NHITS FINAL MODEL WITH DIRECT OVERWRITE ---")

    # --- Check if prerequisite files exist ---
    if not os.path.exists(TRAIN_FILE):
        print(f"ERROR: Training file not found: {TRAIN_FILE}")
        sys.exit(1)
    if not os.path.exists(PREDICT_FILE):
        print(f"ERROR: Prediction file not found: {PREDICT_FILE}")
        sys.exit(1)
    if final_model is None:
        print("FATAL ERROR: final_model was not created/loaded.")
        sys.exit(1)

    # --- Run Enhanced Inference with Direct Overwrite ---
    df_updated_predict = do_inference_seamless_and_overwrite(
        model_to_use=final_model,
        train_file_path=TRAIN_FILE,
        predict_file_path=PREDICT_FILE,
        path_to_sklearn_scalers=SKLEARN_SCALERS_PATH,
        path_to_scaler_info=SCALER_INFO_SAVE_PATH,
        target_cols_list=TARGET_COLUMNS,
        expected_covariate_cols=final_covariate_columns,
        date_col_name=date_col_name,
        bridge_hours=BOUNDARY_CONFIG['bridge_hours'],
        boundary_smooth_hours=BOUNDARY_CONFIG['smooth_hours'],
        anomaly_threshold=BOUNDARY_CONFIG['anomaly_threshold'],
        min_year_train=min_train_year,
        time_feature_cols=TIME_FEATURE_COLS,
        backup_predict_file=True,  # Create backup before overwriting
        reference_output_path=OUTPUT_FILE_REFERENCE  # Save reference copy for debugging
    )

    # --- Plotting Results ---
    print("\n--- Plotting Results ---")
    if df_updated_predict is not None and not df_updated_predict.empty:
        plt.figure(figsize=(16, 8))
        plot_success = False

        try:
            # Load the backup for historical context in plotting
            backup_path = PREDICT_FILE.replace('.parquet', '_backup_gas.parquet')
            if os.path.exists(backup_path):
                df_original_for_plot = pd.read_parquet(backup_path)
                df_original_for_plot['date'] = pd.to_datetime(df_original_for_plot['date'])
            else:
                df_original_for_plot = None

            # Also load some historical data for context
            df_train_for_plot = pd.read_parquet(TRAIN_FILE)
            df_train_for_plot['date'] = pd.to_datetime(df_train_for_plot['date'])
            
            # Get last 72 hours of training data for context
            plot_start = df_train_for_plot['date'].max() - pd.Timedelta(hours=72)
            df_hist_plot = df_train_for_plot[df_train_for_plot['date'] > plot_start]

            # Plot for each target
            for idx, target_col in enumerate(TARGET_COLUMNS):
                # Plot historical data
                if target_col in df_hist_plot.columns and len(df_hist_plot) > 0:
                    plt.plot(df_hist_plot['date'], df_hist_plot[target_col],
                            'k-', label=f'{target_col} Historical', linewidth=1.5)
                    plot_success = True

                # Plot new predictions (from updated predict.parquet)
                if target_col in df_updated_predict.columns:
                    plt.plot(df_updated_predict['date'],
                            df_updated_predict[target_col],
                            'purple', label=f'{target_col} New Prediction', linewidth=2)
                    plot_success = True

                # Plot original values if available (from backup)
                if df_original_for_plot is not None and target_col in df_original_for_plot.columns:
                    # Only plot if there were actual values (not all NaN)
                    original_vals = df_original_for_plot[target_col].dropna()
                    if len(original_vals) > 0:
                        plt.plot(df_original_for_plot['date'],
                                df_original_for_plot[target_col],
                                'b--', label=f'{target_col} Original', linewidth=1, alpha=0.5)

            # Add vertical line at forecast start
            forecast_start = df_updated_predict['date'].min()
            plt.axvline(x=forecast_start, color='red', linestyle=':', alpha=0.7,
                       label='Forecast Start')

        except Exception as e:
            print(f"Error during plotting: {e}")
            traceback.print_exc()

        if plot_success:
            title_text = f"N-HiTS Gas Ratio Forecast (Overwritten in predict.parquet) - {REGION.upper()}\n"
            title_text += f"Model: {MODEL_VERSION_SUFFIX}\n"
            title_text += f"Bridge: {BOUNDARY_CONFIG['bridge_hours']}h, Smooth: {BOUNDARY_CONFIG['smooth_hours']}h"
            if len(features_to_remove) > 0:
                title_text += f"\n({len(features_to_remove)} features removed based on SHAP analysis)"

            plt.title(title_text)
            plt.xlabel("Date")
            plt.ylabel("Natural Gas Ratio")
            plt.ylim(-0.05, 1.05)  # Set limits for ratio
            plt.legend(loc='best')
            plt.grid(True, alpha=0.3)
            plt.tight_layout()

            plot_filename = os.path.join(OUTPUT_DIR, f"{REGION}_gas_ratio_overwrite_plot.png")
            try:
                os.makedirs(os.path.dirname(plot_filename), exist_ok=True)
                plt.savefig(plot_filename, dpi=150)
                print(f"Plot saved: {plot_filename}")
            except Exception as e:
                print(f"Error saving plot: {e}")

            plt.close()
        else:
            print("No data to plot.")
            plt.close()
    else:
        print("No predictions generated, skipping plot.")

    print("\n--- Script Completed Successfully ---")
    print(f"predict.parquet has been OVERWRITTEN with new predictions for: {TARGET_COLUMNS}")
    print(f"Backup saved at: {PREDICT_FILE_BACKUP}")
    print(f"Reference output saved at: {OUTPUT_FILE_REFERENCE}")
    print(f"Features used: {len(final_covariate_columns)} (after removing {len(features_to_remove)} features)")